name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push tekana-user-service
      uses: docker/build-push-action@v2
      with:
        context: ./apps/users-microservice
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-user-service:${{ github.sha }}

    - name: Build and push tekana-wallet-service
      uses: docker/build-push-action@v2
      with:
        context: ./apps/wallet-microservice
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-wallet-service:${{ github.sha }}

    - name: Build and push tekana-transactions-service
      uses: docker/build-push-action@v2
      with:
        context: ./apps/transactions-microservice
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-transactions-service:${{ github.sha }}

    - name: Build and push tekana-api-gateway
      uses: docker/build-push-action@v2
      with:
        context: ./apps/api-gateway
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-api-gateway:${{ github.sha }}