name: Build and Push Docker Images

on:
  push:
    tags:
      - '*staging'
      - '*.production'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from tag
      id: version
      run: |
        # Remove '-staging' suffix to get the version
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION%-staging}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push tekana-user-service
      uses: docker/build-push-action@v3
      with:
        context: ./apps/users-microservice
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-user-service:${{ env.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-user-service:staging
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-user-service:latest

    - name: Build and push tekana-wallet-service
      uses: docker/build-push-action@v3
      with:
        context: ./apps/wallet-microservice
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-wallet-service:${{ env.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-wallet-service:staging
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-wallet-service:latest

    - name: Build and push tekana-transactions-service
      uses: docker/build-push-action@v3
      with:
        context: ./apps/transactions-microservice
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-transactions-service:${{ env.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-transactions-service:staging
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-transactions-service:latest

    - name: Build and push tekana-api-gateway
      uses: docker/build-push-action@v3
      with:
        context: ./apps/api-gateway
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-api-gateway:${{ env.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-api-gateway:staging
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tekana-api-gateway:latest